apiVersion: v1
kind: Service
metadata:
  name: lb-api-belmicro-zebra
  labels:
    app: api-belmicro-zebra
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: api-belmicro-zebra