apiVersion: v1
kind: Service
metadata:
  name: api-belmicro-zebra
  labels:
    app: api-belmicro-zebra
spec:
  type: NodePort
  ports:
  - name: client
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-belmicro-zebra